#!/bin/sh

CUR_LIBRARY=$LIBRARY
printf "checking for -l$CUR_LIBRARY""..."
echo "int main(int argc) {" > test.c
echo "    return 0;" >> test.c
echo "}" >> test.c
cc -o test.o test.c -l$CUR_LIBRARY > /dev/null 2> /dev/null
if test $? = 0; then
	HAVE_LIBRARY=1
	echo "yes"
else
	HAVE_LIBRARY=0
	echo "no"
fi
rm -f test.c test.o
