#!/bin/sh

echo
if test $(uname -s) = "Darwin"; then
	echo "\x1b[95m"
elif test $(uname -a | grep Ubuntu | wc -l) = "1"; then
	/bin/echo -e "\x1b[95m"
else
	echo -e "\x1b[95m"
fi
echo "   ******************************************************************************"
echo "                                   PLEASE READ:"
echo "   It looks like we will have to compile LibreSSL when you do \`make\`."
echo "   If you would like to install it yourself, please do so, then re-run configure."
echo "   LibreSSL takes 10-20 minutes to compile, depending on your computer."
echo
echo "   ******************************************************************************"
if test $(uname -s) = "Darwin"; then
	echo "\x1b[0m"
elif test $(uname -a | grep Ubuntu | wc -l) = "1"; then
	/bin/echo -e "\x1b[0m"
else
	echo -e "\x1b[0m"
fi
