#!/bin/sh

echo
printf "\x1b[95m\n"
echo "   ******************************************************************************"
echo "                                   PLEASE READ:"
echo "   It looks like we will have to compile LibreSSL when you do \`make\`."
echo "   If you would like to install it yourself, please do so, then re-run configure."
echo "   LibreSSL takes 10-20 minutes to compile, depending on your computer."
echo
echo "   ******************************************************************************"
printf "\x1b[0m\n"
